# Generated by Django 5.0.3 on 2024-03-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('slug', models.CharField(db_index=True, help_text="Unique ID from Cloud Mercato's database", primary_key=True, serialize=False, verbose_name='slug')),
                ('name', models.CharField(help_text='As defined by the provider itself', verbose_name='name')),
                ('short_name', models.CharField(help_text='Made from abreviation or initials.', verbose_name='name')),
                ('extra', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, help_text="Unique ID from Cloud Mercato's database", verbose_name='slug')),
                ('name', models.CharField(help_text='As defined by the provider itself', max_length=200, verbose_name='name')),
                ('arch', models.CharField(blank=True, help_text='Architecture powering the CPU', max_length=20, null=True, verbose_name='architecture')),
                ('type', models.CharField(blank=True, help_text='Platform powering the instance', max_length=25, null=True, verbose_name='type')),
                ('cpu', models.PositiveIntegerField(help_text='Number of CPU', verbose_name='CPU')),
                ('ram', models.PositiveIntegerField(help_text='Amount of RAM in MB', verbose_name='RAM')),
                ('root_volume_size', models.PositiveIntegerField(help_text='Amount of GB if a free root volume is given', verbose_name='root volume size')),
                ('extra_volume_size', models.PositiveIntegerField(help_text='Amount of GB if a free extra volume is given', verbose_name='extra volume size')),
                ('gpu', models.PositiveIntegerField(help_text='Number of GPU', verbose_name='GPU')),
                ('gpu_model', models.CharField(blank=True, help_text='GPU model', max_length=100, null=True, verbose_name='GPU')),
                ('max_bandwidth', models.PositiveIntegerField(blank=True, help_text='Network bandwidth in GB/month', null=True, verbose_name='maximum bandwidth')),
                ('extra', models.JSONField(default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='provider')),
            ],
        ),
    ]
