# Generated by Django 5.0.3 on 2024-03-18 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('slug', models.CharField(db_index=True, help_text="Unique ID from Cloud Mercato's database", primary_key=True, serialize=False, verbose_name='slug')),
                ('name', models.CharField(help_text='As defined by the provider itself', verbose_name='name')),
                ('short_name', models.CharField(help_text='Made from abreviation or initials.', verbose_name='name')),
                ('extra', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, help_text="Unique ID from Cloud Mercato's database", verbose_name='slug')),
                ('name', models.CharField(help_text='As defined by the provider itself', verbose_name='name')),
                ('cpu', models.PositiveIntegerField(help_text='Number of CPU', verbose_name='CPU')),
                ('ram', models.PositiveIntegerField(help_text='Amount of RAM in MB', verbose_name='RAM')),
                ('extra', models.JSONField(default=dict)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='provider')),
            ],
        ),
    ]
